.Dd 2015-06-15
.Dt CHIBI-DOC 1
.Os CHIBI-DOC
.Sh NAME
.Nm chibi-doc
.Nd generate docs from Scheme scribble syntax
.Sh SYNOPSIS
.Nm chibi-doc
.Bk -words
.Op Fl hst
.Op Ar file
.Ek
.Pp
.Nm chibi-doc
.Bk -words
.Ar dotted-name.of.module
.Op Ar identifier
.Ek
.Sh DESCRIPTION
.Em chibi-doc
is a tool to generate documentation from the Scheme scribble syntax
from Racket.  It works like a Unix filter, translating from the
current input or a file to standard output.  You can also specify a
module name, with components separated with dots, and it will search
for the module and generate documentation from it automatically from
literate comments in the module or any of its source files.  These
comments are any line beginning with the characters
.Em ;;> .
.Pp
The scribble syntax is described in the manual.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h
Outputs in HTML format (the default).
.It Fl s
Outputs in SXML format.
.It Fl t
Outputs in text format (the default for describing a single variable).
.El
.Sh SEE ALSO
The chibi-scheme home-page:
.Lk http://synthcode.com/wiki/chibi-scheme
.Sh AUTHORS
.An Alex Shinn Aq Mt alexshinn@gmail.com .
